sudo: false

language: php

php:
  - 7.2
  - 7.1

install:
  - composer install --no-dev
  - composer global require phpspec/phpspec:^4 behat/behat:^3.3
  - export PATH=$PATH:$HOME/.composer/vendor/bin/

script:
  - phpspec run --verbose
  - behat --verbose
