sudo: false

language: php

php:
    - 7.4

env:
  global:
    secure: bEwe5CpyxRkTbERUG9stkoa79gxIPN1mGbo4K7VLzxdVAtZYgz64tCuJ5WGJQecMuqsbxVscHJvHKDm6DMZqWbWbyq35QNxmhfSc/0sBI3GN2D6Ptf1mQiQ7fiBHwGaqpfOr5awl3dNgG7t3/xCf6Ul5x3yOZz5BLsu4NQ/cwFrOXSERXX6G0sADtDyVXYSDGf04+AmCpSbGZwzRV76FrjkwLSTqTH6xP6l9kZxe46819B4eB3ZQKyQzCMWFvach0o6roX7jmr7ME51LaO3QGQUebRAZnEmLgSoZscMm5EfMf+ejAQRvWBn3E3c9FtH/4lWjF6JYLcKs7t3d+zzlHSbMAN1V/eHlC8qJ8LVDpgj5KQQlOdjNBUW4yA8ZkAxgYNw0fLq0eewTGwmNFys7EZCjmScMAijF+6+xHO+OlvzLEFHysEpWVSwfQ7f8K3uy7RNYGOxwLQzUWvPupkT2rwe4zYDfcGMf7lHQ6hwN10GwTQirvWUDAcktlOv7ODv04iBShclTtXkuMXf4SZ87T8WHv+TGc6K5UUF0XJW+3YuLYfNV2+qAH3q7gCLwG917sFyU1vJCmkJ8xaDntluGUoggrN3iTEFhKPbHtQMxfEE32XgUSVNn+Vk1LigziEO3KIjx14rw+P2gpMHP0T0I6xjJAUYs4yQRcOafdKH6bBU=

install:
    - make vendor/installed
    - travis_retry wget -O phive.phar https://phar.io/releases/phive.phar
    - travis_retry make tools/installed PHIVE_CMD="php phive.phar"

script:
    - tools/phpspec run --verbose
    - make build
    - tools/behat --suite=debug
    - tools/behat --suite=phar

deploy:
    provider: releases
    api_key:
        secure: KZecGRK+1K1LLpmnhozDie8CknkGx+lLZdDjPXD90CgEDiGyl4vV4k0hR7PM4Lxhdcpw04a48z6j7Z78WCvZQtjrOscmTfz3mw3ofan9MKFr94z4sI0Kgd/qHIbW4XuGaQjSKqyV/3vcLZ861QRIPoD0bkWmuGyC9xttcva0HAr/LVbSZicdxHk249W437evEFgc6rkTD21vQzYNJROaA6cWx2Dg0M8ay5y20H5cC8HBQA4P8Q0IYTOYh6yQmxaRir0UZmKXaly9zR9YtQDCStczq186N9/Znf+7PKjExcqa2mACM0n4spAAiS+1Dao8Wxp3oH/48iCEHgUbzvaxnoh4uqtoJNxnKgXlpsScLZoI6y4kgiJ8d/aEFyF10xjnBFpTAaDCLldmDK4HVl6peXCTdOlnojN4OfbvQdx59nKpgJ5Fa8pl5lupqZH+fL2ntuoGufG9QkMoZ8YcFC9ia8f//V8+gXcXu9eD/wRuO1OeNCXE8/1d6gge66nwslYAXcafbH2Z+m1soYZbvZTn017UQP224ykN+jVg812KMjj/NSBiEPiF2A5KVs073VBqoN4v4JYfMCLuQwVldvxciQSwnbwPGmZ8R6agj/OXmMOiNk6+BGpHZwIPYokJZ/2yczA7CZAX6ZZLAurY8N2RJUNm6Z+jV5NLT2C4IbZTGTo=
    file: giroapp.phar
    skip_cleanup: true
    on:
        tags: true
        repo: byrokrat/giroapp
        condition: ${TRAVIS_PHP_VERSION:0:3} == "7.4"
