sudo: false

language: php

php:
  - 7.1
  - 7.0

install:
  - composer install

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/behat --verbose
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpcs --standard=spec/ruleset.xml spec
