sudo: false

language: php

php:
  - 7.1

install:
  - composer install

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/behat --verbose
  - vendor/bin/phpcs src --standard=PSR2 --ignore=src/ProjectServiceContainer.php
  - vendor/bin/phpcs spec --standard=spec/ruleset.xml
