sudo: false

language: php

php:
  - 7.1

install:
  - composer require chh/bob:^1.0@alpha phpspec/phpspec:^4 behat/behat:^3.3 squizlabs/php_codesniffer:^3

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/behat --verbose
  - vendor/bin/phpcs src --standard=PSR2 --ignore=src/ProjectServiceContainer.php
  - vendor/bin/phpcs spec --standard=spec/ruleset.xml
