services:
    _defaults:
        public: false
        autowire: true

    byrokrat\giroapp\Domain\State\:
        resource: '../src/Domain/State/*'

    byrokrat\giroapp\Workflow\:
        resource: '../src/Workflow/*'

    byrokrat\giroapp\Domain\State\StateCollection:
        class: ~
        arguments:
            - '@byrokrat\giroapp\Domain\State\Active'
            - '@byrokrat\giroapp\Domain\State\AwaitingPause'
            - '@byrokrat\giroapp\Domain\State\AwaitingPayerNumberChange'
            - '@byrokrat\giroapp\Domain\State\AwaitingPayerNumberChangeTransactionUpdate'
            - '@byrokrat\giroapp\Domain\State\AwaitingRevocation'
            - '@byrokrat\giroapp\Domain\State\AwaitingTransactionRegistration'
            - '@byrokrat\giroapp\Domain\State\AwaitingTransactionUpdate'
            - '@byrokrat\giroapp\Domain\State\Error'
            - '@byrokrat\giroapp\Domain\State\MandateCreated'
            - '@byrokrat\giroapp\Domain\State\MandateSent'
            - '@byrokrat\giroapp\Domain\State\NewDigitalMandate'
            - '@byrokrat\giroapp\Domain\State\NewMandate'
            - '@byrokrat\giroapp\Domain\State\PauseSent'
            - '@byrokrat\giroapp\Domain\State\Paused'
            - '@byrokrat\giroapp\Domain\State\PayerNumberChangeSent'
            - '@byrokrat\giroapp\Domain\State\PayerNumberChangeTransactionUpdateSent'
            - '@byrokrat\giroapp\Domain\State\Removed'
            - '@byrokrat\giroapp\Domain\State\RevocationSent'
            - '@byrokrat\giroapp\Domain\State\Revoked'
            - '@byrokrat\giroapp\Domain\State\TransactionRegistrationSent'
            - '@byrokrat\giroapp\Domain\State\TransactionUpdateSent'

    byrokrat\giroapp\Workflow\WorkflowConfigurator:
        class: ~
        arguments:
            -
                - NEW_MANDATE: [MANDATE_CREATED, NEW_MANDATE]
                - NEW_DIGITAL_MANDATE: [MANDATE_CREATED, NEW_DIGITAL_MANDATE]

                - EXPORT: [NEW_MANDATE, MANDATE_SENT]
                - EXPORT: [NEW_DIGITAL_MANDATE, MANDATE_SENT]
                - IMPORT_MANDATE_REGISTERED: [MANDATE_SENT, AWAITING_TRANSACTION_REGISTRATION]
                - EXPORT: [AWAITING_TRANSACTION_REGISTRATION, TRANSACTION_REGISTRATION_SENT]
                - IMPORT_TRANSACTION_ACTIVE: [TRANSACTION_REGISTRATION_SENT, ACTIVE]
                - IMPORT_TRANSACTION_REMOVED: [ACTIVE, ACTIVE]

                - INITIATE_REVOCATION: [ACTIVE, AWAITING_REVOCATION]
                - EXPORT: [AWAITING_REVOCATION, REVOCATION_SENT]
                - IMPORT_MANDATE_REVOKED: [REVOCATION_SENT, REVOKED]
                - IMPORT_TRANSACTION_REMOVED: [REVOCATION_SENT, REVOCATION_SENT]
                - IMPORT_TRANSACTION_REMOVED: [REVOKED, REVOKED]
                - REMOVE: [REVOKED, REMOVED]

                - INITIATE_PAUSE: [ACTIVE, AWAITING_PAUSE]
                - EXPORT: [AWAITING_PAUSE, PAUSE_SENT]
                - IMPORT_TRANSACTION_REMOVED: [PAUSE_SENT, PAUSED]
                - INITIATE_RESTART: [PAUSED, AWAITING_TRANSACTION_REGISTRATION]

                - INITIATE_TRANSACTION_UPDATE: [ACTIVE, AWAITING_TRANSACTION_UPDATE]
                - EXPORT: [AWAITING_TRANSACTION_UPDATE, TRANSACTION_UPDATE_SENT]
                - IMPORT_TRANSACTION_REMOVED: [TRANSACTION_UPDATE_SENT, AWAITING_TRANSACTION_REGISTRATION]

                - INITIATE_PAYER_NUMBER_CHANGE: [ACTIVE, AWAITING_PAYER_NUMBER_CHANGE_TRANSACTION_UPDATE]
                - EXPORT: [AWAITING_PAYER_NUMBER_CHANGE_TRANSACTION_UPDATE, PAYER_NUMBER_CHANGE_TRANSACTION_UPDATE_SENT]
                - IMPORT_TRANSACTION_REMOVED: [PAYER_NUMBER_CHANGE_TRANSACTION_UPDATE_SENT, AWAITING_PAYER_NUMBER_CHANGE]
                - EXPORT: [AWAITING_PAYER_NUMBER_CHANGE, PAYER_NUMBER_CHANGE_SENT]
                - IMPORT_MANDATE_REGISTERED: [PAYER_NUMBER_CHANGE_SENT, AWAITING_TRANSACTION_REGISTRATION]

    byrokrat\giroapp\Domain\State\TransactionDateFactory:
        class: ~
        arguments:
            $dayOfMonth: "@=service('ini').getConfig('trans_day_of_month')"
            $minDaysInFuture: "@=service('ini').getConfig('trans_min_days_in_future')"

    Symfony\Component\Workflow\WorkflowInterface:
        class: Symfony\Component\Workflow\Workflow
        arguments:
            - '@Symfony\Component\Workflow\Definition'
            - '@byrokrat\giroapp\Workflow\MarkingStore'

    Symfony\Component\Workflow\Definition:
        class: ~
        public: true
        factory: ['@Symfony\Component\Workflow\DefinitionBuilder', 'build']

    Symfony\Component\Workflow\DefinitionBuilder:
        class: ~
        arguments: ["@=service('byrokrat\\\\giroapp\\\\Domain\\\\State\\\\StateCollection').getItemKeys()"]
        configurator: ['@byrokrat\giroapp\Workflow\WorkflowConfigurator', 'configureTransitions']
