graph TD

ACTIVE
ERROR
INACTIVE
NEW_MANDATE
NEW_DIGITAL_MANDATE
MANDATE_SENT
MANDATE_APPROVED
REVOKE_MANDATE
REVOCATION_SENT

subgraph REGISTRATION
  NEW_MANDATE--export mandate-->MANDATE_SENT
  NEW_DIGITAL_MANDATE--export mandate-->MANDATE_SENT
  MANDATE_SENT--import registration-->MANDATE_APPROVED
  MANDATE_APPROVED--export transaction-->ACTIVE
  ACTIVE-.import transaction report.->ACTIVE
end

MANDATE_SENT-.import registration error.->ERROR

subgraph REVOCATION
  REVOKE_MANDATE--export revocation-->REVOCATION_SENT
  REVOCATION_SENT--import revocation-->INACTIVE
end

REVOCATION_SENT-.import revocation error.->ERROR

ACTIVE-.->REVOKE_MANDATE
MANDATE_APPROVED-.->REVOKE_MANDATE
